### ISSUE TITLE
Build failure on Vercel deployment

### ISSUE THREAD

**Issue by kevinsegal** [primo-af/primo-server#4]
Tried deploying following the instructions and ran into an issue during the build phase on Vercel:

`'Site' is not exported by node_modules/@primo-app/primo/src/const.js, imported by src/lib/components/Modals/CreateSite.svelte`

I'm relatively new to Svelte so before I go down this rabbit hole trying to fix it, figured I'd bring it to your attention.

**Comment by mateomorris** [comment]
Hey @kevinsegal! Definitely don't try to fix this - this repo isn't quite ready for testing yet, but I'm adding some finishing touches which should be done this week. I'll here again when it's ready.

**Comment by mateomorris** [comment]
Okay @kevinsegal go ahead give it another try, should be good to go now
