### ISSUE TITLE
Vercel deployment failed at build step

### ISSUE THREAD

**Issue by aleksebastian** [primo-af/primo-server#5]
Hello, 

I was unable to deploy with Vercel. Here are the error logs:

17:43:21.552 | Error when using sourcemap for reporting an error: Can't resolve original location of error.

Error: 'locales' is not exported by node_modules/@primo-app/primo/src/const.ts, imported by src/compiler/workers/worker.ts
--
17:43:21.555 | at error (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:158:30)
17:43:21.555 | at Module.error (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:12420:16)
17:43:21.555 | at Module.traceVariable (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:12805:29)
17:43:21.555 | at ModuleScope.findVariable (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:11585:39)
17:43:21.555 | at FunctionScope.findVariable (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:6952:38)
17:43:21.555 | at ChildScope.findVariable (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:6952:38)
17:43:21.555 | at FunctionScope.findVariable (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:6952:38)
17:43:21.555 | at ChildScope.findVariable (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:6952:38)
17:43:21.555 | at ReturnValueScope.findVariable (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:6952:38)
17:43:21.556 | at Identifier.bind (/vercel/path0/node_modules/rollup/dist/shared/rollup.js:6467:40)

**Comment by aleksebastian** [comment]
I was able to successfully build by replacing the locales import with DEFAULTS. Unsure if that's the correct import. 

I then ran into what seems a svelte breaking change where the page said $page.query has been replaced with $page.url.searchParams. So I changed all occurrences in my repo and it seems to be working now.

**Comment by mateomorris** [comment]
@aleksebastian thanks for the report - these issues are fixed now. Let me know if you run into any issues and feel free to open a discussion for anything else 😄
