### ISSUE TITLE
Failing PUT call after update

### ISSUE THREAD

**Issue by aleksebastian** [primo-af/primo-server#6]
Hello again,

I started from scratch to update. No issues building this time or seeing the primo components. However, I am unable to save a site. A 400 is coming back for that PUT call in the browser. Here's a screenshot. 

<img width="1280" alt="Screen Shot 2022-01-13 at 9 24 59 PM" src="https://user-images.githubusercontent.com/65991139/149446559-76e27d55-d6f8-44b6-addd-4b81fd725d27.png">

**Comment by mateomorris** [comment]
@aleksebastian that's weird. You followed all the [instructions](https://github.com/primo-af/primo-server#1-deploy-backend-supabase) for deploying/connecting a Supabase backend?

**Comment by aleksebastian** [comment]
@mateomorris this was my bad. I also disabled email signup in supabase in when I disabled email confirmations.
