### ISSUE TITLE
Not able to create Admin Account

### ISSUE THREAD

**Issue by betterify** [primo-af/primo-server#9]
I am able to set up Primo Server on Vercel successfully!! But I am not able to create an Admin account sign up. It just showed an infinite spin. Please see and help!!

<img width="844" alt="Screenshot 2022-01-22 12 33 08" src="https://user-images.githubusercontent.com/54879853/150628680-770b504b-c8ef-4ce0-8e4a-7e70f0b179f6.png">
p

**Comment by mateomorris** [comment]
This could for several reasons. Could you post a screenshot of your console?

**Comment by betterify** [comment]
@mateomorris Hi thanks for the response. Which console you are talking about? Supabase or Vercel? I am strictly not a developer in that sense.

**Comment by betterify** [comment]
@mateomorris Hi I am sharing with you the screenshot of the browser console. Please let me know in case you require anything else. Thanks.

<img width="857" alt="Screenshot 2022-01-23 16 53 33" src="https://user-images.githubusercontent.com/54879853/150676112-7ca6d49b-5949-484a-9ea3-b8245f7e4a1b.png">

**Comment by mateomorris** [comment]
Looks like the Supabase may not have been set up correctly. Can you confirm that you went through all the setup steps in the README? 

Also, just FYI this project isn't intended for non-developers at the moment. It's very early stage so you'll probably run into things that will make it not worth your time compared to a no-code solution like Wix or Squarespace. Can I ask what you're trying to use it for?

**Comment by betterify** [comment]
@mateomorris Hello Mat I am new to development. I am not saying I don't know development. As I said I successfully set up Supabase. I can share it with you in case you need me to. I wish to use Primo-Server so that I can use Primo App on any device, add users, collaborate with other users, etc. As far as I know, I could successfully set up the Supabase. I am well acquainted with many no-code or low code website solutions like, Wix, Weebly, Squarespace, etc., which I don't want to use. So, please let me know what do you want from me. It appears from the above screenshot the error is at your end. Please offer a concrete solution. Thanks.

**Comment by mateomorris** [comment]
Thanks for the info. This repo is undergoing a lot of changes at the moment since it's still in Alpha, but give me a couple days to look into your issue and I'll post here if I find anything that could help.

**Comment by betterify** [comment]
@mateomorris Oh sure. Waiting ... Thanks 👍

**Comment by Gledros** [comment]
> @mateomorris Oh sure. Waiting ... Thanks 👍

@betterify 

Already fixed on PR #10

It just needs to be merged.

**Comment by mateomorris** [comment]
@betterify we're moving Primo Server over to the [main repo](https://github.com/primo-af/primo/tree/restructure) if you'd like to give it a try there. @Gledros submitted a fix for this issue so it should be fixed now.
